### PR TITLE
Various minor additions

### PR DESCRIPTION
**Pull request by stonier**
These are compatible with the current system (should be).
- `rocon_std_msgs/Float32Stamped.msg` added
- New interactions messages to support enterprise mode.
- Runtime variables removed from the rapp list message (runtime info now in status topic only).

### CODE REVIEW

**Comment by jihoonl** [comment]
Would this require update on rocon_remocon and android remocon?

**Comment by stonier** [comment]
Good question. 

**New Interaction Messages**

This comes into play when 1) interaction manager loads the yaml into msg structures, or 2) a message to load interactions comes from concert services. 

1) only happens inside the interactions manager, no problem here.
2) doesn't use the newly required rapp field, so the message format for them is backwards compatible.

I've been testing on rocon_remocon which is fine. Android should also be, but I haven't tested on that.

**Comment by stonier** [comment]
**Dropping running_rapps**

The `running_rapps` field isn't grepable anywhere inside android code. So that is fine.

It looks like `rocon_qt_app_manager` is using it though. That's unfortunate - I should have deprecated this a long time ago so it wouldn't get used. Should probably delay this until that gets updated.

**Comment by jihoonl** [comment]
issue created in rocon_qt_gui.

https://github.com/robotics-in-concert/rocon_qt_gui/issues/193

**Comment by jihoonl** [comment]
If the message is changing, I think android may complain about MD5sum error. QT version wouldn't do this because it is compiled with new message format as it is in the same workspace.

**Comment by stonier** [comment]
Hmm...good point. Perhaps I should just freeze input coming in from gopher? Or we just start contributing on an indigo-devel?

**Comment by jihoonl** [comment]
I think it would be worth it to have an active development branch. And keep indigo as stable branch.

Then  I can sync indigo and development periodically.

**Comment by jihoonl** [comment]
Let's create `develop` branch for active chaning branch instead of indigo-devel.

So we can just branch out `jade` later.
- `develop` : development branch
- `jade` : jade stable(later if we release)
- `indigo` : indigo stable

**Comment by stonier** [comment]
Closing this as we are moving to other branches.

**Pull request closed without merging**
