### PR TITLE
message refactoring as per discussion

### PR DESCRIPTION
**Pull request by piyushk**

### CODE REVIEW

**Comment by stonier** [comment]
Wonder what happened here since I haven't done much, I'll have to hand merge it. Will drop it in shortly.

**Comment by piyushk** [comment]
I'll pull from the main repo again and remerge. I've realized that the hand merges are problematic for me, and I have to remerge again anyway (or I can refork). 

Also, for rocon_comms, I can't seem to tell when auto merges will fail or not.

**Comment by piyushk** [comment]
Try now, I think I messed up when I synced with the main repo earlier.

**Comment by stonier** [comment]
Ok, done and dusted.

**Pull request merged**
