### PR TITLE
scheduler_msgs: Request message revisions (#60)

### PR DESCRIPTION
**Pull request by jack-oquin**
Please carefully review this update before applying it. The changes are significant, but should be backwards compatible.

Summary: [CHANGELOG for release 0.6.6](https://github.com/jack-oquin/rocon_msgs/blob/hydro-devel/scheduler_msgs/CHANGELOG.rst#066-forthcoming)

Updated message: [Request.msg](https://github.com/jack-oquin/rocon_msgs/blob/hydro-devel/scheduler_msgs/msg/Request.msg)

### CODE REVIEW

**Comment by stonier** [comment]
Busy today jack, but will have a good gander at this and take it for a spin tomorrow.

**Comment by jack-oquin** [comment]
Thanks! I'll be in touch tomorrow. 

Once we are happy with this, I want make a pull request for Hydro, too, for build farm regression testing, which has been quite useful already.

**Comment by stonier** [comment]
Looks good jack.
- When would you use BUSY? On a wait() when there's resources available, but currently engaged elsewhere?
- Don't need to worry about depracated here - I'll just upgrade the concert to match immediately.

**Comment by jack-oquin** [comment]
> - When would you use BUSY? On a wait() when there's resources available, but currently engaged elsewhere?

Yes. 

A `rq.wait(reason=Request.BUSY)` is distinguishable from a `rq.wait(reason=Request.UNAVAILABLE)`. 

The value of that is less than it might seem, because there is no direct representation of _which_ resource is UNAVAILABLE. Once we resolve the resource querying problem, a requester could at least use that reason code to inquire further. Or, in some cases it might give up and let a human deal with the problem.

**Comment by jack-oquin** [comment]
Should I go ahead and remove this stuff?

```
# Deprecated status labels, use the newer equivalents instead:
uint8 ABORTED     = 6
uint8 REJECTED    = 6
uint8 RELEASING   = 5
uint8 RELEASED    = 6
```

That would save another future update.

**Comment by stonier** [comment]
Sure - we can move faster minus one update.

**Comment by jack-oquin** [comment]
see also: utexas-bwi/rocon_scheduler_requests#21

**Comment by stonier** [comment]
This ready to go in jack?

**Comment by jack-oquin** [comment]
Looks good to me.

**Pull request merged**
