### PR TITLE
create rocon_devices message and hue controller msg

### PR DESCRIPTION
**Pull request by dwlee**
Make the rocon_devices_msgs for communication with many device.

### CODE REVIEW

**Comment by stonier** [comment]
Two things to do:
1. Delete the eclipse .project and .pydevproject files. They are copies from scheduler_mgs and will conflict.
2. Update the package version to 0.7.1
3. Add `<run_depend>rocon_device_msgs</run_depend>` to `rocon_msgs/package.xml` (the metapackage).

Unfortunately all packages in a repo have to have the same version for releasing. This matches the others.

**Comment by stonier** [comment]
@dwlee waiting for those fixes 1-3 before merging.

**Comment by jihoonl** [comment]
The fixes has been added.

**Comment by stonier** [comment]
:neckbeard:

**Pull request merged**
