### PR TITLE
also transmitting whether zeroconf is enabled, and which hub uris hav…

### PR DESCRIPTION
**Pull request by asmodehn**
…e been specified.

### CODE REVIEW

**Comment by asmodehn** [comment]
This goes along with https://github.com/robotics-in-concert/rocon_multimaster/pull/347

**Comment by stonier** [comment]
Could use better names here. While they make sense from the point of view of the `HubDiscovery` class, they're a bit enigmatic from a `GatewayInfo` point of view.

How about `scanning_for_hubs_on_zeroconf`, `scanning_for_hubs_on_uris`?

**Comment by asmodehn** [comment]
Yes I was unsure how to name these fields.
Do we want something that long ?

What about :

- discover_zeroconf_hubs
- connect_hub_uris ( main point is hubs are expected to run there... 'scanning' might not be the right wording )

But whatever works for you is fine.

**Comment by stonier** [comment]
It's always scanning in one way or another, even after it's connected so that it knows when it becomes disconnected.

And I've no problem with a long name if the only other option is a short name ambiguous in meaning.

`connect_hub_uris` is ambiguous to me.

**Comment by stonier** [comment]
The two parameters are a pair - should implicate that too via the name. How about

* `discover_hubs_by_zeroconf` : `true/false`
* `discover_hubs_by_uri` : `[]`

**Comment by asmodehn** [comment]
okay, I ll change to that...

--
AlexV

**Pull request merged**
