### PR TITLE
Add flip status

### PR DESCRIPTION
**Pull request by piyushk**
Added string status for flipped connections. This gives feedback to the gateway as to whether the flip was successful or not.

### CODE REVIEW

**Comment by stonier** [comment]
Merging this in immediately as it doesn't break any existing functionality. Can easily rewind or update it later as needed.

**Comment by stonier** [comment]
Oops, I erred on this. `GatewayInfo.msg` changed. I'll quickly go over the accompanying flip pull request and come back to this asap.

**Comment by stonier** [comment]
What are your thoughts on applying the status variable directly to `RemoteRule.msg`? I've quite often been faced with the choice of splitting a message into two parts like this at the cost of really obfuscating the code (here we often have to refer to `remote_rule.remote_rule.rule` which is really awkward) whereas combining them would provide us a single message in which one variable is in some contexts redundant.

**Comment by piyushk** [comment]
:+1: 

I'll update the code both here and in rocon_multimaster and get back to you. I wish I had done what you suggested in the first place, as it would have been a non-breaking change...

**Comment by stonier** [comment]
At times ros messages feel awkward since they don't have _inheritance_, just _composition_ and you end up with situations like this.  I've seen other robot messaging systems that did both in a very computer scientific way and they were very fierce about how good it was too!

It's interesting though, despite being a bit awkward and not exactly technically superior, I wonder if this simplicity is part of its strength and why it has become adopted so comfortably.

**Comment by piyushk** [comment]
Perhaps. I somehow feel that inheritance would be simpler.

Also, I tried to test out adding a status field to RemoteRule.msg instead. That fell a bit flat, as only these 2 constructors are allowed:

```
RemoteRule()
RemoteRule(target_gateway,rule,status)
```

As per http://answers.ros.org/question/27629/default-values-inside-a-message-or-srv-definition/ we cannot specify a default value for the status field, and this means that introducing status into the RemoteRule message is not backwards compatible, and far more disruptive. I'm going to let the separate message be.

**Comment by stonier** [comment]
That's fine.

I think the major increase in complexity with inheritance is not on the user end, but on the implementer's end. Imagine trying to write an implementation in a language which doesn't naturally support inheritance, like C.

**Pull request merged**
